### ISSUE TITLE
Pausebutton in pedalscript

### ISSUE THREAD

**Issue by spomwii** [markvdb/diybookscanner#1]
Is it possible to make a pause button i the pedalscript? Nice to have when your phone calls during a scan.

**Comment by markvdb** [comment]
First priority here is to optimise this for use with an embedded board where there is only one way of interacting: the 1-key foot pedal. May be possible with a double timeout loop.

I'll split up the script eventually. If you're using the script from a pc, it's fairly easy to add a bash while loop and use the space bar for example to pause everything.

**Comment by spomwii** [comment]
Is it possible to check for inactivity and then ask the user if he wants to continue when 15 seconds is reached.
A timer counting down would also be nice.

**Comment by markvdb** [comment]
We need something that can be used in the standalone version too.

After a timeout (10 seconds in the below example), you enter an infinite loop that allows you to choose: either continue scanning (1 press) or download (2 presses).

#! /bin/bash
TMOUT=10
TMOUT2=2

echo "Starting test loop..."
while true
do
  read -n1 press1
  if [ "$press1" == "b" ]; then
    echo "Pedal pressed first time."
    read -n1 -t$TMOUT2 press2
    if [ -z "$press2" ]; then
      echo "Pedal pressed once in two seconds. Performing action one."
    elif [ "$press2" == "b" ]; then
      echo "Pedal pressed twice in two seconds. Performing action two."
      exit
    fi
  fi
done

**Comment by markvdb** [comment]
Fixed in git master. Please test and give feedback if necessary.
