### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by spomwii** [markvdb/diybookscanner#10]
To have an extra way to check if everything went ok during the scan it would be helpful to have a page counter. So if your book is 300 pages you could check the counter to see if 300 pages where scanned.

**Comment by markvdb** [comment]
The minimalist way to count the number of files in a directory on a unix machine is:

<pre>ls -l | wc -l</pre>

Do you think it would be useful to include the number of pages in the debug output of the triggering script?

**Comment by markvdb** [comment]
Closing. Moving to https://github.com/diybookscanner/spreads .
