### ISSUE TITLE
Bookname as folder name

### ISSUE THREAD

**Issue by spomwii** [markvdb/diybookscanner#11]
Is it possible to make the user input the name of the book and use that as the foldername?

**Comment by markvdb** [comment]
We want a standalone raw scanner controller board ready as soon as possible. To keep the delta as small as possible, this should probably be done with command line parameters to the bash script...

http://mywiki.wooledge.org/BashFAQ/035

**Comment by markvdb** [comment]
Closing. Moving all efforts to https://github.com/diybookscanner/spreads .
