### ISSUE TITLE
dynamicly enable and disable gphoto gvfs

### ISSUE THREAD

**Issue by markvdb** [markvdb/diybookscanner#12]
Question from Peter H.: "after running your script to deactivate "competition", how

> can I revert to normal camera USB recognition in Linux/Ubuntu?"

**Comment by linguasoft** [comment]
Thanks, Mark, for opening this thread. Awaiting a "dynamic" solution  ;-)

**Comment by markvdb** [comment]
Hi Peter. I have no Ubuntu 12.04 desktop around right now, but the following works on Debian 7.0 "wheezy", and probably on Ubuntu 12.04 too:

<pre>
gsettings set org.gnome.desktop.media-handling automount "false"
gsettings set org.gnome.desktop.media-handling automount-open "false"
</pre>

Obviously, to reverse:

<pre>
gsettings set org.gnome.desktop.media-handling automount "true"
gsettings set org.gnome.desktop.media-handling automount-open "true"
</pre>

I have updated the wiki documentation https://github.com/markvdb/diybookscanner/wiki/Software-triggering-on-Debian-GNU-Linux#avoiding-competition-for-our-cameras to reflect this.
