### ISSUE TITLE
Identify a reliable sd card speed test

### ISSUE THREAD

**Issue by markvdb** [markvdb/diybookscanner#13]
...and document in wiki. See also issue with card in #5 .

**Comment by SimonAM** [comment]
http://ubuntuforums.org/showthread.php?t=1155245&page=2

"You can test SD Card / MicroSD Card with H2testtw 1.4
Use it with wine 1.3.34 ..."

**Comment by markvdb** [comment]
The latest development version does not require a fast sd card anymore, as the images are downloaded to the attached computer directly.

**Comment by SimonAM** [comment]
Hello
I have been trying to use simultanious triggering and automatic downloading
as per these instructions:
https://github.com/markvdb/diybookscanner/wiki/chdkptp
I guess its for raspberry pi and not for my ubuntu 12.04 computer.

How do i install simultanious triggering and automatical downloading for
ubuntu?

2013/11/22 Mark Van den Borre notifications@github.com

**Comment by markvdb** [comment]
Hello Simon,

I am testing, documenting and extending the new setup as we speak. You can
follow this at https://github.com/jbaiter/spreads . Closing this issue as
it has become irrelevant to the new and much improved setup.

Kind regards,

Mark
http://diybookscanner.eu

2014/1/18 SimonAM notifications@github.com

> Hello
> I have been trying to use simultanious triggering and automatic
> downloading
> as per these instructions:
> https://github.com/markvdb/diybookscanner/wiki/chdkptp
> I guess its for raspberry pi and not for my ubuntu 12.04 computer.
> 
> How do i install simultanious triggering and automatical downloading for
> ubuntu?
> 
> 2013/11/22 Mark Van den Borre notifications@github.com
> 
> > The latest development version does not require a fast sd card anymore,
> > as
> > the images are downloaded to the attached computer directly.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/markvdb/diybookscanner/issues/13#issuecomment-29105490>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/markvdb/diybookscanner/issues/13#issuecomment-32683664
> .

## 

Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726
