### ISSUE TITLE
Cameras would not zoom in as they should

### ISSUE THREAD

**Issue by schlumerkeck** [markvdb/diybookscanner#14]
After running:
https://github.com/markvdb/diybookscanner/blame/master/misc/test_keypedal.sh
the cameras would not zoom in as they should.

We changed: 'lua while(get_zoom()<3) do click("zoom_in") end'
to: 'lua set_zoom(20)'

The cameras zoomed in happily.
Other ideas would be appreciated.

**Comment by markvdb** [comment]
Closing. Moving all efforts to https://github.com/diybookscanner/spreads
