### ISSUE TITLE
Downloading and deleting all files, including firmware

### ISSUE THREAD

**Issue by mitar** [markvdb/diybookscanner#15]
When I trigger download and delete, PS.FI2 file is downloaded and deleted as well. I put it onto the card as part of the CHDK firmware.

Looking at the code, I am not sure why is there a `A` prefix to directory path?

```
gphoto2 --port $GPHOTOCAM1 --recurse -D A/store00010001/DCIM/; true
```

**Comment by markvdb** [comment]
Closing. Moving all efforts to https://github.com/diybookscanner/spreads .
