### ISSUE TITLE
Trigger both cameras at the same time

### ISSUE THREAD

**Issue by spomwii** [markvdb/diybookscanner#4]
Trigger both cameras at the same time would save some scanning time.

**Comment by markvdb** [comment]
Right now, the effort is to get the ptpcam based solution stable and high quality.

There is some experimental support for this in the chdkptp multicam module, but that was still stabilising last time I checked.

**Comment by markvdb** [comment]
First commit towards parallel triggering: 63bd7e7867

**Comment by linguasoft** [comment]
I am happy to see that there is still some action on this forum since all my previous emails have remained unanswered. Is this project still alive?

**Comment by markvdb** [comment]
This project certainly is alive!

I am a little worried to read "since all my previous emails have remained unanswered". I suspect our spam filters. Contacting you in private to find out what went wrong!

P.S. To avoid this kind of probem, you can now also reach us by phone (answering machine most of the time, but still) at +371 67 859 899 (fixed line, Riga, Latvia, EU).

**Comment by linguasoft** [comment]
Yes, it appears that none of my e-mails went through, as we had this situation already once before (half a year ago). If you cannot set your spam filters in a way that they recognize known contacts, please provide me with an alternative e-mail of yours (webmail like Yahoo or Gmail, as they use their own spam filters that do not suppress email from other webmail providers). Asking people to call a frequently unattended phone makes no sense in my opinion, especially not for discussing technical questions (I try to avoid phone in general as I do not want to disturb other people at work and vice versa).

Sorry for doing this discussion here which is certainly an inappropriate place. Maybe you can remove it or start a separate thread? Regards, Peter

**Comment by markvdb** [comment]
Experiments with gnu parallel on the raspberry pi yields no usable results.  The ptp sessions in chdkptp get confused. Unclear yet if this is because more than one ptp session is open at a time, or because of limited threading capacities...

**Comment by markvdb** [comment]
This is working in https://github.com/diybookscanner/spreads . Closing to concentrate all efforts there.
