### ISSUE TITLE
autofocus lock

### ISSUE THREAD

**Issue by markvdb** [markvdb/diybookscanner#8]
test autofocus lock

**Comment by SimonAM** [comment]
I might have misunderstood something but...

After following the instrucitons here:
https://github.com/markvdb/diybookscanner/blob/master/misc/settings.md
I set the AFL in P-mode. But when the script automatically turns the camera to recording mode the AFL is unlocked

**Comment by markvdb** [comment]
Manual focus seems to still provoke unstability in the camera with CHDK 1.3. So still not enabled in the latest development build.

**Comment by markvdb** [comment]
Enabled and tested working in  4a68daef3b

**Comment by markvdb** [comment]
Closing ticket. Moving to new code base at https://github.com/diybookscanner/spreads
